### ISSUE TITLE
${{ }} sections not rendering properly

### ISSUE THREAD

**Issue by woneill** [WyriHaximus/blog.wyrihaximus.net#181]
Comparing source/_posts/2023-03-03-testing-github-actions.markdown to the blog itself, it appears the the `${{ }}` sections in examples are showing up as `$0`.

Once I viewed the source, the post was much more informative 😃

**Comment by WyriHaximus** [comment]
Thanks for the heads up @woneill :+1: . Just hotfixed them and pushed the updated page to the CDN

**Comment by woneill** [comment]
Looks good!

**Comment by WyriHaximus** [comment]
Great! Thanks again for the heads up :+1:
